version: 2
jobs:
  build_node_v10:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo_v10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test


  build_node_v8:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo_v8

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  publish_to_npm:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mv npmrc-env .npmrc

      - run:
          name: Publish to NPM (only if a new version has been tagged)
          command: if [ "$(npm show codius version)" != "$(npm ls --depth=-1 2>/dev/null | head -1 | cut -f 1 -d " " | cut -f 2 -d @)" ] ; then npm publish ; fi

workflows:
  version: 2
  build:
    jobs:
      - build_node_v10
      - build_node_v8
      - publish_to_npm:
          requires:
            - build_node_v10
          filters:
            branches:
              only:
                - master
